### ISSUE TITLE
<client>.anime.getCharacters(anime_id) doesn't return images

### ISSUE THREAD

**Issue by xMiyuka** [rizzzigit/jikan4.js#10]
This could have been an intentional thing however, I wanted to make a request assuming it was that. When I call the `getCharacters()` function I'd like that an array of JPG and WebP images are returned similarly to how `getPictures()` work. Reason is, reading Jikans official API documentation [here](https://docs.api.jikan.moe/#tag/anime/operation/getAnimeCharacters), it shows their API does return the characters images by default however, your package seems to split that feature into a separate thing. It would be convenient to have all the characters and all their images in one call instead of having to only be able to get a single image per character id. It would also be really nice to have the "About" part of the character also in the object too.

result from `<client>.anime.getCharacters(anime_id)  //array[0].character` 
```
CharacterMeta {
  id: 737,
  url: URL {
    href: 'https://myanimelist.net/character/737/Kouta',
    origin: 'https://myanimelist.net',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'myanimelist.net',
    hostname: 'myanimelist.net',
    port: '',
    pathname: '/character/737/Kouta',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },

  type: 'Character',
  name: 'Kouta'
}
```

Wanted / expected outcome
```
CharacterMeta {
  id: 737,
  url: URL {
    href: 'https://myanimelist.net/character/737/Kouta',
    origin: 'https://myanimelist.net',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'myanimelist.net',
    hostname: 'myanimelist.net',
    port: '',
    pathname: '/character/737/Kouta',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  image: ImageFormatCollection {
    jpg: Image {
      small: null,
      default: [URL],
      medium: null,
      large: null,
      maximum: null
    },
    webp: Image {
      small: [URL],
      default: [URL],
      medium: null,
      large: null,
      maximum: null
    }
  },
  type: 'Character',
  name: 'Kouta',
  about: 'long thing for about.'
}
```

I don't wish to sound like I'm unsatisfied with your module, it's actually quite the opposite. I think this out of the past ones I've used this is certainly the best. For what I'm trying to create, this would be far-more convenient if this could become a reality. Thank you for your time and effort into making this amazing project. <3

**Comment by rizzzigit** [comment]
Hello again, thank you for catching this issue.

I have added the image property to CharacterMeta and PersonMeta. However, the image property in the PersonMeta is nullable because some endpoints (like /manga/\<id>\/) return manga.authors[0] without the image property.

About the `about` property: Unfortunately I cannot add this because Jikan API does not seem to return it in every CharacterMeta. You have to create a separate http request for every character to get the `about` property, or in this case, call client.characters.get(id) in jikan4.js.

**Comment by xMiyuka** [comment]
Makes sense. The about part isn't 100% needed for my project so it's not a huge deal. I made a discord bot will pagination things so making an HTTP request for each about would lead to a rate limit 100%. Same goes for the null able images, I only use anime images for characters and not manga so I should be okay. One other suggestion since I assume you will see this is that airing status that is returned via Jikan4.js. An example status that is returned is 'FinishedAiring", aesthetically it could be neater to return it with a space xD. I'm sure you have your reasoning for that. A simple .replace() is an obvious fix for the user of Jikan4.js to add the space, but could save a couple characters for us developers. <3
