### ISSUE TITLE
limited results for English searches

### ISSUE THREAD

**Issue by Omixxx** [rizzzigit/jikan4.js#8]
hello developers! <br> I am writing to you because I have some doubts about the `search()` function you can call on the `Jikan.Clien` `anime` or `manga` respectively. 
well I would like to ask you why this search is only done on the default title but not on the synonyms of a particular series. <br>
For example searching for ***demon slayer***  in `client.anime.search()` and then filtering so that the title includes the word demon slayer (to avoid all irrelevant results), only returns me two results which are respectively
- Demon Slayer Kimetsu No Yaiba Asakusa Arc
- Demon Slayer Kimetsu No Yaiba Tsuzumi Mansion Arc

however when I search for Kimetsu No Yaiba the api returns a whole series of results, containing in the `titles` field also the English synonym 'demon slayer'

Could you tell me why this happens and if there is a way I can get all the results for kimetsu no yaiba back even when searching for 'demon slayer'?

i really appreciate the work you are and have done, it is one of the most complete and well done libraries in my opinion, and i hope you can help me

**Comment by rizzzigit** [comment]
Thank you for your kind words!

I tried replicating this issue and I got the same results. Unfortunately this is a problem with the API itself, and I don't know how exactly the API searching works. I asked the API developers about this and I will give an update soon.

**Comment by rizzzigit** [comment]
Sadly, it seems that only default titles are indexed for searching by Jikan API. Hopefully the API devs will fix it soon.
